version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  git-demo:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    container_name: git-demo
    environment:
      - GIT_URL
      - GIT_TEMPLATE
      - GIT_ACCESS_TOKEN
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./logs/:/logs
    ports:
      - "8080:8080"
      - "8085:8085"
    depends_on:
      - redis
