spring:
  application:
    name: git.demo
  config:
    import: optional:file:.env[.properties]

github:
  api:
    url: https://api.github.com
    template: 2022-11-28
    token: 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
  weights:
    stargazers_count: 1.5
    forks_count: 2.0
    updated_at: -0.1
