server:
  port: 8080

spring:
  application:
    name: git.demo
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      time_in_minutes: ${REDIS_TIME_IN_MINUTES}

github:
  api:
    url: ${GIT_URL}
    template: ${GIT_TEMPLATE}
    token: ${GIT_ACCESS_TOKEN}
  weights:
    stargazers_count: 1.5
    forks_count: 2.0
    updated_at: 50
